apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops-challenge

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: devops-challenge-backend:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          # Liveness probe:
          # Checks whether the Flask application is alive.
          # Kubernetes can restart the container if this repeatedly fails.
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          # Readiness probe:
          # Checks whether the Flask application is ready to receive traffic.
          # If this fails, Kubernetes removes the Pod from Service endpoints.
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          # PostgreSQL configuration
          env:
            - name: POSTGRES_HOST
              value: postgres-service

            - name: POSTGRES_PORT
              value: "5432"

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
